### ISSUE TITLE
Regression: v0.3 does not work on AMD Graphic Drivers 

### ISSUE THREAD

**Issue by Philip6294** [Louka3000/OpenVR-Dynamic-Resolution#25]
Starting from [v0.3.0-rc.1](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/releases/tag/v0.3.0-rc.1) the app crashes on startup because of missing nvml.dll. 

0.2.2 works fine. 

I'm running a RX 6800XT and AMD Driver version 23.3.2.

**Comment by Louka3000** [comment]
Hi, @Philip6294 I knew this was gonna happen but hoped it wasn't... The problem is importing an NVIDIA-only dll for VRAM monitoring.
Thankfully, the fix is simple. Please test this and confirm if it works for you.

[OpenVR-Dynamic-Resolution.zip](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/files/12222384/OpenVR-Dynamic-Resolution.zip)

**Comment by Philip6294** [comment]
That version still crashes with the same error message

**Comment by Louka3000** [comment]
> That version still crashes with the same error message

Turns out it was a much harder fix ;-;
The nvml library is now included at runtime, so I can just discard the fact that it doesn't import without crashing the app, and instead disables VRAM monitoring. 
Please try this:
[OpenVR-Dynamic-Resolution.zip](https://github.com/Louka3000/OpenVR-Dynamic-Resolution/files/12235409/OpenVR-Dynamic-Resolution.zip)

**Comment by Philip6294** [comment]
I just tried the 0.3.2 release and that one is working again.

**Comment by Louka3000** [comment]
Didn’t mean to close the issue, merging the PR did it ahah
Glad to hear it works now anyways ^^
